name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Build application
      run: |
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ./publish

    - name: Upload Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: BuildArtifact
        path: ./publish
